### ISSUE TITLE
Weid behavior in php

### ISSUE THREAD

**Issue by phaalonso** [smjonas/inc-rename.nvim#30] opened 2023-01-25 14:24 UTC
When programming in PHP, the plugin has a weird behavior:
![image](https://user-images.githubusercontent.com/26033899/214587979-1df5e84b-83f8-49d4-acbb-32d87bf62a63.png)

Sorry for this monstrosity. I'm new to this codebase and still in the process of refactoring it and implementing best practices

Obs: working fine on other languages
![image](https://user-images.githubusercontent.com/26033899/214588763-b3500f4e-4cdc-4830-92fb-1b1ebdc10896.png)

**Comment by smjonas** [comment] 2023-01-25 20:08
Thanks for reporting! Which LSP server are you using (run `:LspInfo`)?

**Comment by phaalonso** [comment] 2023-01-25 20:11
I'm using lsp-zero, I tried a few more times and the rename worked fine, the problem seem to be in the way that the plugin is rendering the new name

**Comment by smjonas** [comment] 2023-01-25 20:13
`lsp-zero` is just a wrapper around the built-in LSP. Can you tell me the active LSP servers that the `:LspInfo` command is showing?

**Comment by phaalonso** [comment] 2023-01-26 23:47
Sorry for the delay, the active lsps are intelephense and phpactor

**Comment by smjonas** [comment] 2023-01-27 11:24
I can't reproduce this since neither `intelephense` nor `phpactor` seem to have the rename capability for me, so `vim.lsp.buf.rename()` always results in "Rename, no matching language servers with rename capability". 

Could you tell me the output of the commands `:lua =require("lsp-zero").build_options("intelephense", {})` and `:lua =require("lsp-zero").build_options("phpactor", {})`? (Maybe `lsp-zero` adds something to the config)

**Comment by phaalonso** [comment] 2023-01-27 12:09
Sorry, I wasnt able to copy the output of the files so I recorded it

intelephense:
[Screencast from 01-27-2023 09:03:42 AM.webm](https://user-images.githubusercontent.com/26033899/215082641-c9de97e2-832c-4280-99c4-ada815f6b263.webm)


phpactor:
[Screencast from 01-27-2023 09:04:43 AM.webm](https://user-images.githubusercontent.com/26033899/215082650-4fdf1ced-3dce-40e6-86fc-9c0044920b6e.webm)

My dotfiles are in this [repository](https://github.com/phaalonso/dotfiles), mayabe it will help in reproducing it

**Comment by smjonas** [comment] 2023-01-27 14:01
Alright I only just now realized that only the paid version of `intelephense` supports renaming (source: https://intelephense.com/). Since I haven't bought the paid version I can't debug this further. Can you please use the branch `debug` (add `branch = "debug"` in your packer config), rename a variable in a PHP file, then tell me what is printed in `:messages`?

**Comment by phaalonso** [comment] 2023-01-27 14:36
Strange, I also don't have the paid version and the renaming is working, maybe lsp-zero or my config is bypassing this somehow?  🤔

Well, I managed to extract the log this time running `put = execute('messages')` in a empty file
<details>
<summary> Log </summary>

```log
{ {
    range = {
      ["end"] = {
        character = 15,
        line = 15
      },
      start = {
        character = 8,
        line = 15
      }
    },
    uri = "file:///home/pedro/programacao/projetos/IxopPlay-Api/app/Http/Controllers/FabricantesController.php"
  }, {
    range = {
      ["end"] = {
        character = 19,
        line = 18
      },
      start = {
        character = 12,
        line = 18
      }
    },
    uri = "file:///home/pedro/programacao/projetos/IxopPlay-Api/app/Http/Controllers/FabricantesController.php"
  }, {
    range = {
      ["end"] = {
        character = 19,
        line = 19
      },
      start = {
        character = 12,
        line = 19
      }
    },
    uri = "file:///home/pedro/programacao/projetos/IxopPlay-Api/app/Http/Controllers/FabricantesController.php"
  }, {
    range = {
      ["end"] = {
        character = 23,
        line = 27
      },
      start = {
        character = 16,
        line = 27
      }
    },
    uri = "file:///home/pedro/programacao/projetos/IxopPlay-Api/app/Http/Controllers/FabricantesController.php"
  }, {
    range = {
      ["end"] = {
        character = 73,
        line = 28
      },
      start = {
        character = 66,
        line = 28
      }
    },
    uri = "file:///home/pedro/programacao/projetos/IxopPlay-Api/app/Http/Controllers/FabricantesController.php"
  } }
LSP[phpactor][Info] ... scanned 0 references confirmed 2 ...
LSP[phpactor][Info] Found 5 reference(s)
{ {
    range = {
      ["end"] = {
        character = 8,
        line = 15
      },
      start = {
        character = 8,
        line = 15
      }
    },
    uri = "file:///home/pedro/programacao/projetos/IxopPlay-Api/app/Http/Controllers/FabricantesController.php"
  }, {
    range = {
      ["end"] = {
        character = 12,
        line = 18
      },
      start = {
        character = 12,
        line = 18
      }
    },
    uri = "file:///home/pedro/programacao/projetos/IxopPlay-Api/app/Http/Controllers/FabricantesController.php"
  }, {
    range = {
      ["end"] = {
        character = 12,
        line = 19
      },
      start = {
        character = 12,
        line = 19
      }
    },
    uri = "file:///home/pedro/programacao/projetos/IxopPlay-Api/app/Http/Controllers/FabricantesController.php"
  }, {
    range = {
      ["end"] = {
        character = 16,
        line = 27
      },
      start = {
        character = 16,
        line = 27
      }
    },
    uri = "file:///home/pedro/programacao/projetos/IxopPlay-Api/app/Http/Controllers/FabricantesController.php"
  }, {
    range = {
      ["end"] = {
        character = 66,
        line = 28
      },
      start = {
        character = 66,
        line = 28
      }
    },
    uri = "file:///home/pedro/programacao/projetos/IxopPlay-Api/app/Http/Controllers/FabricantesController.php"
  } }
Renamed 5 instances in 1 file
</details>

**Comment by smjonas** [comment] 2023-01-29 19:34
To me it looks like the cause of this issue is that either `phpactor` or `intelephense` respond with incorrect values for the `range.data.character` value (notice how `start` and `end` are always the same):
```
range = {
      ["end"] = {
        character = 8,
        line = 15
      },
      start = {
        character = 8,
        line = 15
      }
    },
```
I have updated the `debug` branch, can you see if your issue is now fixed?

**Comment by smjonas** [comment] 2023-01-29 19:37
Also, can you tell me whether this was caused by `intelephense` or by `phpactor` (e.g. by disabling either one of them)? I'd like to file an issue there.

**Comment by phaalonso** [comment] 2023-01-29 22:41
I just run some tests, and it seems to be caused by phpactor

**Comment by phaalonso** [comment] 2023-01-29 22:42
![image](https://user-images.githubusercontent.com/26033899/215359897-2820ee16-383c-4e85-86e3-7aca639e0c14.png)
![image](https://user-images.githubusercontent.com/26033899/215359900-8d901199-5187-4f27-9706-79860945e319.png)

**Comment by smjonas** [comment] 2023-01-30 07:25
Thanks! Is this fixed for you now with the latest update on the `debug` branch?

**Comment by phaalonso** [comment] 2023-02-02 14:47
Sorry for the delay, at the moment the debug branch still has the bug but it's different than before. I noticied that the rename is running using the phpactor lsp and not intelephense

![image](https://user-images.githubusercontent.com/26033899/216356120-d55a46cd-d839-4062-bc55-aad018b55506.png)

**Comment by smjonas** [comment] 2023-03-03 16:44
Could you provide me with an example PHP project where I can test the renaming? I now installed phpactor but the LSP server won't attach to the root directory for some reason so I can't test your issue (also, single file support does not seem supported so I can't just use a single test file):
![image](https://user-images.githubusercontent.com/40792180/222777493-cd9940d5-aa70-4b49-949e-71eadf306042.png)

I tested it with [this](https://github.com/Dahkenangnon/PhpFromZero) PHP repo but still no luck.

**Comment by phaalonso** [comment] 2023-03-06 01:58
Strange, I tried refactoring in the mentioned repository and is working on my computer. Maybe because of lsp-zero or mason

Can you give a try to [this repository](https://github.com/ishanvyas22/laravel-todo-list-api)? If still doesn't work, I think that you will need configure the root path to a `.git` or `composer.json`

**Comment by smjonas** [comment] 2023-10-26 22:44
Phpactor has now added a fix for this on master (https://github.com/phpactor/phpactor/pull/2352) so this issue should be fixed now 🎉.

**Closed** 2023-10-26 22:43 UTC
Labels: bug, third-party issue
