### ISSUE TITLE
Error on rename

### ISSUE THREAD

**Issue by antoyo** [smjonas/inc-rename.nvim#53] opened 2024-03-26 13:05 UTC
Hi.
Sometimes, when I try to rename an item, I get the following error:
```
[inc-rename] An error occurred in the preview function. Please report this error here: https://github.com/smjonas/inc-rename.nvim/issues:
Error executing Lua callback: ...are/nvim/plugged/inc-rename.nvim/lua/inc_rename/init.lua:264: Invalid 'end_col': out of range
stack traceback:
^I[C]: in function 'nvim_buf_set_text'
^I...are/nvim/plugged/inc-rename.nvim/lua/inc_rename/init.lua:264: in function 'apply_highlights_fn'
^I...are/nvim/plugged/inc-rename.nvim/lua/inc_rename/init.lua:306: in function <...are/nvim/plugged/inc-rename.nvim/lua/inc_rename/init.lua:210>
```
I'm not exactly sure how to reproduce the issue, though, but perhaps I could point you to a project of mine where this happens if needed.
Thanks to fix the issue.

**Comment by smjonas** [comment] 2024-03-26 23:02
Hi, thanks for letting me know, I haven't seen this issue occur before. Do you perhaps remember which language server was active during the rename? If it occurs again, please don't hesitate to send me more details as you offered. Thank you!

**Comment by antoyo** [comment] 2024-03-26 23:20
This is `rust-analyzer`.

Here's the output of `:LspInfo`:

```

**Comment by Moerliy** [comment] 2024-04-30 12:30
I'm encountering this one too, but only on my larger projects. I think it doesn't matter which language server it is because I have the same behavior with tsserver, clangd and pyright. 
My guess is the issue lies with the live preview when renaming. It can handle one character change but with the next one there is no preview anymore. On confirming the rename the following error pops up:
```bash
      "[inc-rename] An error occurred in the preview function. Please report this error here: https://github.com/smjonas/inc-rename.nvim/issues:
Error executing Lua callback: .../share/nvim/lazy/inc-rename.nvim/lua/inc_rename/init.lua:328: Invalid 'end_col': out of range
stack traceback:
	[C]: in function 'nvim_buf_set_text'
	.../share/nvim/lazy/inc-rename.nvim/lua/inc_rename/init.lua:328: in function 'apply_highlights_fn'
	.../share/nvim/lazy/inc-rename.nvim/lua/inc_rename/init.lua:374: in function <.../share/nvim/lazy/inc-rename.nvim/lua/inc_rename/init.lua:278>
Active language servers: { "tsserver" }
Buffer name: MY_CURRENT_BUFFER
```

**Comment by smjonas** [comment] 2024-05-02 18:02
@Moerliy Do you have an example project I can try to reproduce this with? I am unable to reproduce this error with tsserver. Please also let me know in which file the error occurred and on what identifier if possible.

**Comment by Moerliy** [comment] 2024-05-02 22:57
@smjonas the projects I encountered it are unfortunately locked behind company policies. If I have some time tomorrow I will dig into it and try to find one that I can share.

**Comment by Moerliy** [comment] 2024-05-03 17:20
@smjonas as promised a way of getting the issue consistently. If it doesn't work just let me know and we try something else.
1. Use the [zod](https://github.com/colinhacks/zod) project written in typescript. So you will need the tsserver as a lsp.
2. Open up src/types.ts
3. move down to line 93 and try renaming `SyncParseReturnType`.
4. After deleting 3 characters the preview buffer closes and if you confirm the rename with enter you will get the error message from above.

Something I noticed and could have the same root problem:
1. Same project, same file
2. line 92 and try renaming `ParseContext`.
3. Add a couple of characters and have a look at the preview. With every new character added to the rename, the previously added characters should appear again with every new character you add. Hard to describe but the number of characters shown in the preview is the factorial of the number of characters added to the rename.
(not sure if you can reproduce it tho because that behavior is a bit less predictable)

**Comment by smjonas** [comment] 2024-05-03 18:11
@Moerliy Thanks a lot for the detailed instructions! That should help greatly with debugging. I will try to have a look at this next week :)

**Comment by dsully** [comment] 2024-05-10 16:23
I'm also seeing this with `rust-analyzer`. Also using nightly and `noice.nvim` if that matters.

**Comment by smjonas** [comment] 2024-05-11 11:27
Hi @Moerliy,
unfortunately I could not reproduce the issue you described:
![image](https://github.com/smjonas/inc-rename.nvim/assets/40792180/fd3cde91-8d30-46b8-bbfb-d98b48563f49)
When renaming `SyncParseReturnType`, it looks just fine, too.

Which version of `tsserver` are you using? I installed it with mason and am on the latest version (`4.3.3`).

**Comment by Moerliy** [comment] 2024-05-14 16:31
I'm using mason too so the same version.

Maybe there are some issues with other plugins i installed. 
If you want you can have a look at my nvim [dotfiles](https://github.com/Moerliy/dotfiles/tree/master/.config/nvim). The should work out of the box if you ignore the chatgpt warning.

**Comment by marcomayer** [comment] 2024-05-30 07:28
I get the same error sporadically but much more often since updating to nvim 0.10. Using the latest gopls language server.

**Comment by joaomendoncaa** [comment] 2024-05-30 16:27
Using `lua_ls` (neovim 0.10.0) and getting the same issue. Thanks to anyone who jumps on this.

```lua
"[inc-rename] An error occurred in the preview function. Please report this error here: https://github.com/smjonas/inc-rename.nvim/issues:
Error executing Lua callback: .../share/nvim/lazy/inc-rename.nvim/lua/inc_rename/init.lua:337: Invalid 'end_col': out of range
stack traceback:
^I[C]: in function 'nvim_buf_set_text'
^I.../share/nvim/lazy/inc-rename.nvim/lua/inc_rename/init.lua:337: in function 'apply_highlights_fn'
^I.../share/nvim/lazy/inc-rename.nvim/lua/inc_rename/init.lua:383: in function <.../share/nvim/lazy/inc-rename.nvim/lua/inc_rename/init.lua:287>
Active language servers: { "lua_ls" }
Buffer name: /home/joao/lab/config/dotfiles/nvim/lua/utils/flags.lua
```

**Comment by joaomendoncaa** [comment] 2024-05-30 16:28
Using `lua_ls` (neovim 0.10.0) and getting the same issue. Thanks to anyone who jumps on this.

```lua
"[inc-rename] An error occurred in the preview function. Please report this error here: https://github.com/smjonas/inc-rename.nvim/issues:
Error executing Lua callback: .../share/nvim/lazy/inc-rename.nvim/lua/inc_rename/init.lua:337: Invalid 'end_col': out of range
stack traceback:
^I[C]: in function 'nvim_buf_set_text'
^I.../share/nvim/lazy/inc-rename.nvim/lua/inc_rename/init.lua:337: in function 'apply_highlights_fn'
^I.../share/nvim/lazy/inc-rename.nvim/lua/inc_rename/init.lua:383: in function <.../share/nvim/lazy/inc-rename.nvim/lua/inc_rename/init.lua:287>
Active language servers: { "lua_ls" }
```

**Comment by joaomendoncaa** [comment] 2024-05-30 19:41
> @joaomendoncaa thanks for reporting, would you mind sharing the file contents where this error occurred?

I tried to re-open the directory [where it happened](https://github.com/joaomendoncaa/config/blob/b051ad449fec201b3a6729a1325aea3fc9f476ee/dotfiles/nvim/lua/utils/flags.lua#L3) and sadly couldn't reproduce it again. But I've had this issue on other ocasions with other LSPs. (hope that helps)

Meanwhile, I found another quirk when renaming certain namespaces and recorded it. (also happened before with other LSPs, but this is on `lsp_ls`) See video bellow on how `:IncRename` is somehow infinitely repeating the characters I'm typing: 

https://github.com/smjonas/inc-rename.nvim/assets/57664150/24df4bee-abaf-4b1e-aee6-dfd23d498d50


This might be happening for a thousand different reasons so, if needed, you can message me to help you debugging this, I don't have a lot of time to investigate it myself sadly.

Twitter: https://x.com/joaomendoncaaaa
Telegram: https://t.me/joaomendoncaaa

**Comment by smjonas** [comment] 2024-05-30 20:33
Thank you, I was now able to produce the error with your dotfiles. I could also reproduce the other error with `inccommand=split` which I will look into.

**Comment by joaomendoncaa** [comment] 2024-05-30 20:43
Awesome! Thank you for all your work Jonas. 🙏

**Comment by smjonas** [comment] 2024-06-02 21:12
@joaomendoncaa I fixed a bug that only occurred with `inccommand=split` (that might explain the fact that I never noticed any issues). Can you update the plugin and let me know if you can still reproduce the errors you mentioned? Thanks for your help.

**Comment by Moerliy** [comment] 2024-06-02 22:43
@smjonas I just saw this and did some quick tests. Both, the example I mentioned earlier in the thread and and other in my bigger project seem to work. The lsp's I tested were tsserver, clangd and pyright. 
I did some load tests in c++ too. Did renaming for symbols with 100+ mentions across 10 files.

**Comment by joaomendoncaa** [comment] 2024-06-02 23:33
> @joaomendoncaa I fixed a bug that only occurred with `inccommand=split` (that might explain the fact that I never noticed any issues). This suspicion is also supported by the fact that antoyo and Moerliy also have `set inccommand=split` in their config.
> 
> Can you update the plugin and let me know if you can still reproduce the errors you mentioned? Thanks for your help.

Hey! Awesome news! 🙌 

I roughly tested it aswell and the renaming feature seems to be working with only 2 minor issues:

- Highlights are miss-placed;
- `inccommand=split` quickfix list is only updating the last item correctly (although all of them get correctly renamed)

_Quick demo_

https://github.com/smjonas/inc-rename.nvim/assets/57664150/98408013-c139-44a3-bb20-41ea23bc4c00

**Comment by smjonas** [comment] 2024-06-03 07:53
@joaomendoncaa Thank you for testing as well! I also noticed this other issue - at least there is no crash now though ;) I will try to fix it this week.

**Comment by joaomendoncaa** [comment] 2024-06-04 18:56
Hey @smjonas! Hope you're safe and sound but I'm yet again the bearer of bad news! 😂 

Found another bug on renaming where it doesn't replace the correct characters at all. This time around I have 3 clients attached to the buffer (`tsserver`, `typescript-tools` and `tailwindcss`).

The demo bellow will try to replace `initialSettings` to `initial` in 2 places with the following errors:

- `(...) initialSettings: Settings (...)` to `initialgs` 
- `(...) writable<Settings>(initialSettings);` to `writable<Settings>(initial`

So it both deletes more than the length of the replaced characters and sometimes leaves unwanted characters in place. I can't share the repo but let me know if I can give you anything else useful to debug the issue.

https://github.com/smjonas/inc-rename.nvim/assets/57664150/06c816bf-15d7-48b9-ba84-6dcb23c25521

**Comment by smjonas** [comment] 2024-06-06 21:11
@joaomendoncaa
> inccommand=split quickfix list is only updating the last item correctly (although all of them get correctly renamed)

This issue should now be fixed, I added a test and can't reproduce it anymore

> Found another bug on renaming where it doesn't replace the correct characters at all. This time around I have 3 clients attached to the buffer (tsserver, typescript-tools and tailwindcss).

The issue seems to be that you're using `typescript-tools` and `tsserver` at the same time. Make sure to uninstall tsserver (this is also stated in the `typescript-tools` readme). 

Let me know if there are any remaining issues and thanks for all the great feedback and help! :)

**Comment by joaomendoncaa** [comment] 2024-06-06 21:38
🫶 🫵  @smjonas 

![image](https://github.com/smjonas/inc-rename.nvim/assets/57664150/cc0f33e3-9167-4ed9-b105-fee56e70133f)

![image](https://github.com/smjonas/inc-rename.nvim/assets/57664150/af50e6d5-c1f4-4f3a-8627-eea6ad06bc10)

**Comment by smjonas** [comment] 2024-06-24 20:26
Since there hasn't been any activity in this thread since the last commits, I will close this issue assuming the bugs have been fixed :) Please open a new issue if anyone still experiences similar issues.

**Closed by smjonas** 2024-06-24 20:26 UTC
Labels: bug
