### ISSUE TITLE
Rust - Inlined format args not renamed

### ISSUE THREAD

**Issue by ConnorWay32** [smjonas/inc-rename.nvim#39] opened 2023-06-14 10:18 UTC
Renaming a variable with uninlined format args works as expected, however inlined format args are not affected.
```rust
let a = 5;
println!("{}", a);
println!("{a}");
```
becomes
```rust
let b = 5;
println!("{}", b);
println!("{a}");
```

**Comment by smjonas** [comment] 2023-06-14 13:29
This is a `rust-analyzer` issue. Duplicate of https://github.com/rust-lang/rust-analyzer/issues/11296.

**Closed by smjonas** 2023-06-14 13:29 UTC
